version: "3"
services:
  prom-elastic-alert:
    build:
      context: ../
#    image: elastic-alert:latest
    restart: always
    depends_on:
      - alertmanager
    expose:
      - 9003
    ports:
      - "9003:9003"
    volumes:
      - ./config.yaml:/etc/config.yaml
      - ../rules:/rules/demo
    command: ["--config=/etc/config.yaml", "--debug"]
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2000M
    healthcheck:
      test: [ "CMD-SHELL", "ps aux | grep 'main.go' | grep -v 'grep' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - prom-elastic-alert-net
  alertmanager:
    image: prom/alertmanager:v0.23.0
    user: root
    restart: always
#    depends_on:
#      - prom-alert
    volumes:
      - ./alertmanager/conf:/etc/alertmanager
      - ./alertmanager/data:/alertmanager
    expose:
      - 9093
    ports:
      - "9093:9093"
    healthcheck:
      test: [ "CMD-SHELL", "netstat -lntp | grep '9093' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - prom-elastic-alert-net
#  prom-alert:
#    image: feiyu563/prometheus-alert:v-4.6.1
#    restart: always
#    volumes:
#      - ./prom-alert/conf:/app/conf
#      - ./prom-alert/db:/app/db
#      - ./prom-alert/logs:/app/logs
#    expose:
#      - 8080
#    ports:
#      - "38080:8080"
#    healthcheck:
#      test: [ "CMD-SHELL", "netstat -lntp | grep '8080' || exit 1" ]
#      interval: 10s
#      timeout: 10s
#      retries: 3
#    networks:
#      - prom-elastic-alert-net

  redis:
    image: redis
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - prom-elastic-alert-net
#
#  otel-collector:
#    image: otel/opentelemetry-collector-contrib:0.75.0
#    command: [ "--config=/etc/otel-collector.yaml" ]
#    volumes:
#      - ../shared/otel-collector.yaml:/etc/otel-collector.yaml
#    ports:
#      - "4317:4317"   # otlp grpc
#      - "4318:4318"   # otlp http

  prometheus:
    image: prom/prometheus:v2.43.1
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    depends_on:
      - prom-elastic-alert
    networks:
      - prom-elastic-alert-net

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./shared/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    restart: always
    ports:
      - "14268:14268" # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095"   # tempo grpc
      - "9411:9411"   # zipkin
    networks:
      - prom-elastic-alert-net
  grafana:
    image: grafana/grafana:9.4.3
    volumes:
      - ./shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
    networks:
      - prom-elastic-alert-net
networks:
  prom-elastic-alert-net: