apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elastic-alert.fullname" . }}-rules
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elastic-alert.labels" . | nindent 4 }}
data: