# Default values for elastic-alert.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: ghcr.io
  repository: openinsight-proj/elastic-alert
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8cd03486b387f66a6f97f27f3f035dafea73f289"

configReloader:
  image:
    registry: docker.m.daocloud.io
    repository: jimmidyson/configmap-reload
    pullPolicy: IfNotPresent
    tag: "v0.3.0"
  command:
    args:
      - -webhook-url=http://127.0.0.1:8080/-/reload
      - -volume-dir=/rules/customs

  resources: {}
#    limits:
#      cpu: 200m
#      memory: 50Mi
#    requests:
#      cpu: 40m
#      memory: 10Mi

extraVolumes: []
# extraVolumes:
#   - name: custom-rules-configmap
#     configMap:
#       name: custom-rules-config

extraVolumeMounts: []
# mountpath must be the value of rules_folder configured in setup config,
# because prometheus configmap reloader does not support folder recursive: https://github.com/prometheus-operator/prometheus-operator/blob/70e9708371a6dbdad716deab4fc6fc9a2d89ed1b/cmd/prometheus-config-reloader/main.go#LL65C2-L65C12
# e.g. /rules
# extraVolumeMounts:
#   - name: custom-rules-configmap
#     mountPath: /rules/custom-rules

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

serviceMonitor:
  enabled: false
  interval: "1s"
  additionalLabels: {}
#    operator.insight.io/managed-by: insight
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
