apiVersion: v1
kind: Service
metadata:
  name: {{ include "elastic-alert.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elastic-alert.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9003
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 8081
      targetPort: reloader-web
      protocol: TCP
      name: reloader-web
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "elastic-alert.selectorLabels" . | nindent 4 }}
