{{- if .Values.serviceAccount.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "elastic-alert.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elastic-alert.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "update", "create", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elastic-alert.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elastic-alert.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "elastic-alert.fullname" . }}-rb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elastic-alert.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "elastic-alert.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "elastic-alert.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
