{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
  name: {{ .Release.Name }}-elastic-alert
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - honorLabels: true
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "elastic-alert.selectorLabels" . | nindent 6 }}
{{- end -}}
