{{- if .Values.rules.builtIn.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "elastic-alert.fullname" . }}-built-in-rules
  labels:
    {{- include "elastic-alert.labels" . | nindent 4 }}
data:
  insight-error-log-demo.rule.yaml: |-
    unique_id: "InsightErrorLog"
    enabled: true
    es:
      addresses:
        - "{{ .Values.rules.es.address }}"
      username: "{{ .Values.rules.es.username }}"
      password: "{{ .Values.rules.es.password }}"
      conn_timeout: 300
      version: "v7"
    index: "insight-es-k8s-logs-*"
    run_every:
      seconds: 5
    query:
      type: "frequency"
      query_string: 'log:error'
      config:
        timeframe:
          minutes: 5
        num_events: 5
      labels:
        alertname: "NginxErrorLog"
        instance: "localhost"
        severity: "warning"
        for_time: "5min"
        threshold: "5"
      annotations:
        description: "insight k8s log error 日志条数 {{ `{{ .value }}` }} > {{ `{{ .threshold }}` }}"
        summary: "insight elastic alert"
{{- end }}