name: Release Charts

on:
  # Requires manual trigger
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.1
        with:
          version: v3.4.1

      - name: Release Helm Chart
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: helm-chart/
        env:
          CR_TOKEN: "${{ secrets.ACTIONS_TOKEN }}"

